# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calv1.0.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, math

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 370)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 2, 0, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 3, 0, 1, 2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 4, 0, 1, 2)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 5, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.sin)
        self.pushButton_2.clicked.connect(self.cos)
        self.pushButton_3.clicked.connect(self.arcsin)
        self.pushButton_4.clicked.connect(self.arctan)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "计算器"))
        self.label.setText(_translate("MainWindow", "输入："))
        self.label_2.setText(_translate("MainWindow", "结果："))
        self.pushButton.setText(_translate("MainWindow", "sin"))
        self.pushButton_2.setText(_translate("MainWindow", "cos"))
        self.pushButton_3.setText(_translate("MainWindow", "arcsin"))
        self.pushButton_4.setText(_translate("MainWindow", "arctan"))

    def sin(self):
        num = self.lineEdit.text()
        print(num)
        self.lineEdit_2.setText(str(math.sin(float(num))))
        pass

    def cos(self):
        num = self.lineEdit.text()
        print(num)
        self.lineEdit_2.setText(str(math.cos(float(num))))
        pass

    def arcsin(self):
        num = self.lineEdit.text()
        print(num)
        if (float(num) >= -1.0) and (float(num) <= 1.0):
            self.lineEdit_2.setText(str(math.asin(float(num))))
        else:
            from PyQt5.QtWidgets import QMessageBox  # 导入QMessageBox类
            QMessageBox.warning(MainWindow, "warning", "输入错误", QMessageBox.Yes | QMessageBox.No,QMessageBox.Yes)


    def arctan(self):
        num = self.lineEdit.text()
        print(num)
        self.lineEdit_2.setText(str(math.atan(float(num))))
        pass


if __name__=='__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()  #创建窗口对象
    ui = Ui_MainWindow()  #创建PyQt设计的窗口对象
    ui.setupUi(MainWindow)  #调用PyQt窗体的方法对窗体对象进行初始化设置
    MainWindow.show()  #显示窗体
    sys.exit(app.exec_())  #程序关闭时退出进程